/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FramesYpaneles;

import DAO.ControlClientes;
import Negocio.Cliente;
import java.awt.BorderLayout;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos
 */
public class AdministrarClientes extends javax.swing.JPanel {

    ControlClientes control = new ControlClientes();
    DefaultTableModel modelo;

    /**
     * Creates new form AdministrarClientes
     */
    public AdministrarClientes() {
        initComponents();

        modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombres");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Empresa");
        modelo.addColumn("Email");
        modelo.addColumn("Telefono");
        modelo.addColumn("Rfc");
        this.tblClientes.setModel(modelo);
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txt_consultar = new javax.swing.JTextField();
        btn_Consultar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_Empresa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_rfc = new javax.swing.JTextField();
        Btn_Guardar = new javax.swing.JButton();
        Btn_Cancelar = new javax.swing.JButton();
        Btn_Editar = new javax.swing.JButton();
        Btn_Eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        txt_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_nombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Apellidos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu Clientes_1.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, 70));

        txt_consultar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(252, 178, 1)));
        txt_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_consultarActionPerformed(evt);
            }
        });
        add(txt_consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 530, -1));

        btn_Consultar.setBackground(new java.awt.Color(252, 178, 1));
        btn_Consultar.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        btn_Consultar.setForeground(new java.awt.Color(49, 54, 56));
        btn_Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-buscar-cliente-30.png"))); // NOI18N
        btn_Consultar.setText("Consultar ID");
        btn_Consultar.setBorder(null);
        btn_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConsultarActionPerformed(evt);
            }
        });
        add(btn_Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 170, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Empresa:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 80, -1));

        txt_Empresa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(252, 178, 1)));
        txt_Empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmpresaActionPerformed(evt);
            }
        });
        add(txt_Empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 530, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("RFC:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 50, -1));

        txt_rfc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(252, 178, 1)));
        add(txt_rfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 530, -1));

        Btn_Guardar.setBackground(new java.awt.Color(252, 178, 1));
        Btn_Guardar.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        Btn_Guardar.setForeground(new java.awt.Color(49, 54, 56));
        Btn_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-guardar-30.png"))); // NOI18N
        Btn_Guardar.setText("Guardar");
        Btn_Guardar.setBorder(null);
        Btn_Guardar.setBorderPainted(false);
        Btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GuardarActionPerformed(evt);
            }
        });
        add(Btn_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 170, 40));

        Btn_Cancelar.setBackground(new java.awt.Color(252, 178, 1));
        Btn_Cancelar.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        Btn_Cancelar.setForeground(new java.awt.Color(49, 54, 56));
        Btn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-cancelar-2-30.png"))); // NOI18N
        Btn_Cancelar.setText("Cancelar");
        Btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CancelarActionPerformed(evt);
            }
        });
        add(Btn_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 170, 40));

        Btn_Editar.setBackground(new java.awt.Color(252, 178, 1));
        Btn_Editar.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        Btn_Editar.setForeground(new java.awt.Color(49, 54, 56));
        Btn_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-editar-fila-30.png"))); // NOI18N
        Btn_Editar.setText(" Editar");
        Btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EditarActionPerformed(evt);
            }
        });
        add(Btn_Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 170, 40));

        Btn_Eliminar.setBackground(new java.awt.Color(252, 178, 1));
        Btn_Eliminar.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        Btn_Eliminar.setForeground(new java.awt.Color(49, 54, 56));
        Btn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-eliminar-30.png"))); // NOI18N
        Btn_Eliminar.setText("Eliminar");
        Btn_Eliminar.setBorder(null);
        Btn_Eliminar.setBorderPainted(false);
        Btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EliminarActionPerformed(evt);
            }
        });
        add(Btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 170, 40));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 800, 220));

        txt_id.setEditable(false);
        txt_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(252, 178, 1)));
        add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 530, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("ID:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 30, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nombres:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 80, -1));

        txt_nombres.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(252, 178, 1)));
        txt_nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombresActionPerformed(evt);
            }
        });
        txt_nombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombresKeyTyped(evt);
            }
        });
        add(txt_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 530, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Apellidos:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 80, -1));

        txt_Apellidos.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(252, 178, 1)));
        txt_Apellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ApellidosKeyTyped(evt);
            }
        });
        add(txt_Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 530, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Mail:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 40, -1));

        txt_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(252, 178, 1)));
        txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emailFocusLost(evt);
            }
        });
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_emailKeyTyped(evt);
            }
        });
        add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 530, 20));

        txt_telefono.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(252, 178, 1)));
        txt_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonoActionPerformed(evt);
            }
        });
        txt_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefonoKeyTyped(evt);
            }
        });
        add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 530, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Telefono:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 80, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_consultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_consultarActionPerformed

    private void btn_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConsultarActionPerformed
        Integer id = Integer.parseInt(this.txt_consultar.getText());
        Cliente userBuscar = control.buscarCliente(id);
        DefaultTableModel model = (DefaultTableModel) tblClientes.getModel();
        int rowCount = model.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }

        Object rowData[] = new Object[9];
        rowData[0] = userBuscar.id;
        rowData[1] = userBuscar.nombres;
        rowData[2] = userBuscar.apellidos;
        rowData[3] = userBuscar.empresa;
        rowData[4] = userBuscar.email;
        rowData[5] = userBuscar.telefono;
        rowData[6] = userBuscar.rfc;
        rowData[7] = userBuscar.comentarios;
        rowData[8] = userBuscar.calificacion;
        model.addRow(rowData);
    }//GEN-LAST:event_btn_ConsultarActionPerformed

    private void Btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GuardarActionPerformed
        Cliente cliente = new Cliente();
        cliente.setNombres(txt_nombres.getText());
        cliente.setApellidos(txt_Apellidos.getText());
        cliente.setEmpresa(txt_Empresa.getText());
        cliente.setEmail(txt_email.getText());
        cliente.setTelefono(Long.parseLong(txt_telefono.getText()));
        cliente.setRfc(txt_rfc.getText());

        if (control.insertarCliente(cliente)) {
            JOptionPane.showMessageDialog(null, "Se Agrego con Exito", "Cliente", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Fallo al guardar", "Cliente", JOptionPane.INFORMATION_MESSAGE);
        }
        actualizarTabla();
    }//GEN-LAST:event_Btn_GuardarActionPerformed

    private void Btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CancelarActionPerformed
        limpiarCampos();
        actualizarTabla();
    }//GEN-LAST:event_Btn_CancelarActionPerformed

    private void Btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EditarActionPerformed
        Cliente clienteEditar = new Cliente();
        clienteEditar.setId(Integer.parseInt(txt_id.getText()));
        clienteEditar.setNombres(txt_nombres.getText());
        clienteEditar.setApellidos(txt_Apellidos.getText());
        clienteEditar.setEmpresa(txt_Empresa.getText());
        clienteEditar.setEmail(txt_email.getText());
        clienteEditar.setTelefono(Long.parseLong(txt_telefono.getText()));
        clienteEditar.setRfc(txt_rfc.getText());

        if (control.modificarCliente(clienteEditar)) {
            JOptionPane.showMessageDialog(null, "Se Edito con exito", "Cliente", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Fallo al editar", "Cliente", JOptionPane.INFORMATION_MESSAGE);
        }
        actualizarTabla();
    }//GEN-LAST:event_Btn_EditarActionPerformed

    private void Btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EliminarActionPerformed
        Cliente clienteEliminar = new Cliente();
        clienteEliminar.setId(Integer.parseInt(txt_id.getText()));
        clienteEliminar.setNombres(txt_nombres.getText());
        clienteEliminar.setApellidos(txt_Apellidos.getText());
        clienteEliminar.setEmpresa(txt_consultar.getText());
        clienteEliminar.setEmail(txt_email.getText());
        clienteEliminar.setTelefono(Long.parseLong(txt_telefono.getText()));
        clienteEliminar.setRfc(txt_rfc.getText());

        if (control.eliminarCliente(clienteEliminar)) {
            JOptionPane.showMessageDialog(null, "Se Elimino con Exito", "Cliente", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Fallo al eliminar", "Cliente", JOptionPane.INFORMATION_MESSAGE);
        }
        actualizarTabla();
    }//GEN-LAST:event_Btn_EliminarActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        int fila = tblClientes.getSelectedRow();
        if (fila != -1) {
            txt_id.setText(tblClientes.getValueAt(fila, 0).toString());
            txt_nombres.setText(tblClientes.getValueAt(fila, 1).toString());
            txt_Apellidos.setText(tblClientes.getValueAt(fila, 2).toString());
            txt_Empresa.setText(tblClientes.getValueAt(fila, 3).toString());
            txt_email.setText(tblClientes.getValueAt(fila, 4).toString());
            txt_telefono.setText(tblClientes.getValueAt(fila, 5).toString());
            txt_rfc.setText(tblClientes.getValueAt(fila, 6).toString());
        }
    }//GEN-LAST:event_tblClientesMouseClicked

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonoActionPerformed

    private void txt_nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombresActionPerformed

    private void txt_EmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmpresaActionPerformed

    private void txt_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }

        if (txt_telefono.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_telefonoKeyTyped

    private void txt_nombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombresKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_nombresKeyTyped

    private void txt_ApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ApellidosKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_ApellidosKeyTyped

    private void txt_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyTyped
        
    }//GEN-LAST:event_txt_emailKeyTyped

    private void txt_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusLost
       // Definir la expresión regular para validar el correo electrónico
        String expresionRegular = "^[a-zA-Z0-9_+&*-]+(?:\\."+ 
                                "[a-zA-Z0-9_+&*-]+)*@" + 
                                "(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        Pattern pattern = Pattern.compile(expresionRegular);
        
        // Validar el correo electrónico
        Matcher matcher = pattern.matcher(txt_email.getText());
        if (!matcher.matches()) {
           JOptionPane.showMessageDialog(null,"El correo no es válido");
        } 
    }//GEN-LAST:event_txt_emailFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Cancelar;
    private javax.swing.JButton Btn_Editar;
    private javax.swing.JButton Btn_Eliminar;
    private javax.swing.JButton Btn_Guardar;
    private javax.swing.JButton btn_Consultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txt_Apellidos;
    private javax.swing.JTextField txt_Empresa;
    private javax.swing.JTextField txt_consultar;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JTextField txt_rfc;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables

    private void actualizarTabla() {
        List<Cliente> list = control.listarClientes();
        DefaultTableModel model = (DefaultTableModel) tblClientes.getModel();
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        Object rowData[] = new Object[9];
        for (int i = 0; i < list.size(); i++) {
            rowData[0] = list.get(i).id;
            rowData[1] = list.get(i).nombres;
            rowData[2] = list.get(i).apellidos;
            rowData[3] = list.get(i).empresa;
            rowData[4] = list.get(i).email;
            rowData[5] = list.get(i).telefono;
            rowData[6] = list.get(i).rfc;
            rowData[7] = list.get(i).comentarios;
            rowData[8] = list.get(i).calificacion;
            model.addRow(rowData);
        }
    }

    private void limpiarCampos() {
        txt_id.setText("");
        txt_nombres.setText("");
        txt_Empresa.setText("");
        txt_Apellidos.setText("");
        txt_email.setText("");
        txt_telefono.setText("");
        txt_rfc.setText("");
        txt_consultar.setText("");
    }

}
