/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FramesYpaneles;

import java.awt.BorderLayout;

/**
 *
 * @author Carlos
 */
public class JFMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFMenu
     */
    public JFMenu() {
        initComponents();
        setSize(1110,850);
        setLocation(0,0);
        setLocationRelativeTo(this);
        PanelMain.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMain = new javax.swing.JPanel();
        btnAdmEmpleados = new javax.swing.JButton();
        btnComentarios = new javax.swing.JButton();
        btnAdmClientes = new javax.swing.JButton();
        btnMensajes = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1485, 892));
        setPreferredSize(new java.awt.Dimension(1485, 892));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMain.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelMainLayout = new javax.swing.GroupLayout(PanelMain);
        PanelMain.setLayout(PanelMainLayout);
        PanelMainLayout.setHorizontalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        PanelMainLayout.setVerticalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );

        getContentPane().add(PanelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, -40, 1080, 900));

        btnAdmEmpleados.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        btnAdmEmpleados.setText("Administrar Empleados");
        btnAdmEmpleados.setBorder(null);
        btnAdmEmpleados.setBorderPainted(false);
        btnAdmEmpleados.setContentAreaFilled(false);
        btnAdmEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmEmpleadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdmEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 249, 44));

        btnComentarios.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        btnComentarios.setText("Comentarios y Ratings");
        btnComentarios.setBorder(null);
        btnComentarios.setBorderPainted(false);
        btnComentarios.setContentAreaFilled(false);
        btnComentarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComentariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnComentarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, 249, 44));

        btnAdmClientes.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        btnAdmClientes.setText("Administrar Clientes");
        btnAdmClientes.setBorder(null);
        btnAdmClientes.setBorderPainted(false);
        btnAdmClientes.setContentAreaFilled(false);
        btnAdmClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmClientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdmClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 249, 44));

        btnMensajes.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        btnMensajes.setText("Mensajes Publicitarios");
        btnMensajes.setBorder(null);
        btnMensajes.setBorderPainted(false);
        btnMensajes.setContentAreaFilled(false);
        btnMensajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMensajesActionPerformed(evt);
            }
        });
        getContentPane().add(btnMensajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 249, 44));

        btnSalir.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 740, 249, 44));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Orange (6).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdmClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmClientesActionPerformed
        AdministrarClientes clientes = new AdministrarClientes();
        clientes.setSize(1008,750);
        clientes.setLocation(0,0);
        
        PanelMain.removeAll();
        PanelMain.add(clientes,BorderLayout.CENTER);
        PanelMain.revalidate();
        PanelMain.repaint();
    }//GEN-LAST:event_btnAdmClientesActionPerformed

    private void btnComentariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComentariosActionPerformed
       
        ComentariosYRating comentariosYrating = new ComentariosYRating();
        comentariosYrating.setSize(1008,750);
        comentariosYrating.setLocation(0,0);
        
        PanelMain.removeAll();
        PanelMain.add(comentariosYrating,BorderLayout.CENTER);
        PanelMain.revalidate();
        PanelMain.repaint();
                                  
    }//GEN-LAST:event_btnComentariosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMensajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensajesActionPerformed
       MensajesPublicitarios mensajes = new MensajesPublicitarios();
        mensajes.setSize(1008,750);
        mensajes.setLocation(0,0);
        
        PanelMain.removeAll();
        PanelMain.add(mensajes,BorderLayout.CENTER);
        PanelMain.revalidate();
        PanelMain.repaint();
    }//GEN-LAST:event_btnMensajesActionPerformed

    private void btnAdmEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmEmpleadosActionPerformed
        PanelMain.setVisible(true);
        AdministrarEmpleados empleados = new AdministrarEmpleados();
        empleados.setSize(1008,750);
        empleados.setLocation(0,0);
        
        PanelMain.removeAll();
        PanelMain.add(empleados,BorderLayout.CENTER);
        PanelMain.revalidate();
        PanelMain.repaint();
        
    }//GEN-LAST:event_btnAdmEmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMain;
    private javax.swing.JButton btnAdmClientes;
    private javax.swing.JButton btnAdmEmpleados;
    private javax.swing.JButton btnComentarios;
    private javax.swing.JButton btnMensajes;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
